#COPY THIS FILE AND NAME IT config.yaml TO MAKE IT WORK

#Comment out if you have none, some features wont work though.
#To get a key go to https://wallhaven.cc and sign up.
#Then go to https://wallhaven.cc/settings/account and copy the key in
# api_key: u7U2BeUbZdaQ6yh6rW5PAZdWbyOUwLCi
#The options are Sfw, Sketchy, SketchyAndSfw, Nsfw, and Any. Note: only SFW works without a apiKey
purity: Sfw
#This is in seconds. Dont set it lower than 2 seconds
new_picture_delay: 10
#Format num1 num2, for example : 1920 1080
min_resolution:
  w: 1920
  h: 1080
#An array of all the possibly querys.
#categories is not needed, and does not always work properly. This is out of our hands.
#Sometimes commenting out categories can increase accuracy
query_data:
  - query: dogs
    # categories:
  - query: cats
    # categories:
